### ISSUE TITLE
ENH Request: could you add a note about how to install in readme?

### ISSUE THREAD

**Issue by nickeubank** [alfredxing/one#1]
I tried just putting in `~/application support/library/sublime text 3/packages/one` but having trouble...

**Comment by rands0n** [comment]
I want this package too! Can you put an info about how to install @alfredxing?

**Comment by alfredxing** [comment]
OK, just realized I didn't have this yet!
However please keep in mind that this is far from a finished theme right now!

**Comment by alfredxing** [comment]
Just added: https://github.com/alfredxing/one/blob/master/README.md#preliminary-installation-instructions

If it doesn't work, feel free to re-open this issue! 😄
